--- 
- 
  name: "Setup stage"
  become: true
  hosts: stage
  tasks: 
    -
      name: "Ensure default-jdk package is present"
      apt:
        name: default-jdk
        update_cache: yes
        state: present
    -
      name: "Ensure maven package is present"
      apt:
        name: maven
        state: present
    -
      name: "Ensure git package is present"
      apt:
        name: git
        state: present
    -
      name: "Ensure directory /home/ubuntu/build/ present"
      file:
        path: /home/ubuntu/build/
        state: directory
    -
      name: "Ensure project files downloaded from git"
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/ubuntu/build
        clone: yes
    -
      name: "Ensure maven compile project"
      command: mvn -f /home/ubuntu/build/pom.xml clean package
    -
      name: "Ensure tomcat8 package is present"
      fetch:
        method: pull
        src: /home/ubuntu/build/target/hello-1.0.war
        dest: /tmp/
        flat: yes

-
  name: "Setup prod"
  become: true
  hosts: prod
  tasks:
    -
      name: "Ensure default-jdk package is present"
      apt:
        name: default-jdk
        update_cache: yes
        state: present
    -
      name: "Ensure tomcat8 package is present"
      apt:
        name: tomcat8
        update_cache: yes
        state: present
    -
      name: "Ensure tmp java application is present"
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat8/webapps
    -
      name: "Ensure tomcat8  service is started"
      service:
        name: tomcat8
        state: restarted
